"""Facility 6: Executive Briefing.

Produces the final human-readable summary of a completed workflow. When
an Anthropic API key is configured, the summary is generated by Claude;
otherwise -- or if the API call fails for any reason -- a deterministic
template produces an equally complete summary so a missing/invalid key
never fails the workflow, only degrades the polish of its narrative.
"""

from __future__ import annotations

import logging

import anthropic

from app.models.schemas import ExecutiveBriefing, ExtractedInvoiceData, RiskAssessment

logger = logging.getLogger(__name__)


class ExecutiveBriefingService:
    def __init__(self, anthropic_api_key: str, anthropic_model: str) -> None:
        self._model = anthropic_model
        self._client = anthropic.Anthropic(api_key=anthropic_api_key) if anthropic_api_key else None

    def generate(
        self,
        workflow_id: str,
        extracted: ExtractedInvoiceData,
        risk: RiskAssessment,
        outcome: str,
        approval_result: str,
    ) -> ExecutiveBriefing:
        summary: str | None = None
        generated_by = "deterministic_fallback"

        if self._client is not None:
            try:
                summary = self._generate_with_anthropic(workflow_id, extracted, risk, outcome, approval_result)
                generated_by = "anthropic"
            except Exception:
                logger.warning(
                    "Anthropic briefing generation failed for workflow %s; falling back to deterministic summary.",
                    workflow_id,
                    exc_info=True,
                )

        if summary is None:
            summary = self._deterministic_summary(extracted, risk, outcome, approval_result)

        return ExecutiveBriefing(
            vendor=extracted.vendor,
            amount=extracted.amount,
            po_number=extracted.po_number,
            risk_score=risk.risk_score,
            approval_result=approval_result,
            workflow_outcome=outcome,
            summary=summary,
            generated_by=generated_by,
        )

    def _generate_with_anthropic(
        self,
        workflow_id: str,
        extracted: ExtractedInvoiceData,
        risk: RiskAssessment,
        outcome: str,
        approval_result: str,
    ) -> str:
        anomaly_lines = "\n".join(f"- [{a.severity}] {a.code}: {a.detail}" for a in risk.anomalies) or "- none"
        prompt = (
            "Write a concise 2-4 sentence executive briefing for a finance leader summarizing the "
            "outcome of an automated invoice approval workflow. Be factual and specific, no filler.\n\n"
            f"Workflow ID: {workflow_id}\n"
            f"Vendor: {extracted.vendor or 'unknown'}\n"
            f"PO Number: {extracted.po_number or 'unknown'}\n"
            f"Amount: {extracted.amount if extracted.amount is not None else 'unknown'}\n"
            f"Risk score: {risk.risk_score}/100\n"
            f"Anomalies:\n{anomaly_lines}\n"
            f"Approval result: {approval_result}\n"
            f"Workflow outcome: {outcome}\n"
        )
        response = self._client.messages.create(
            model=self._model,
            max_tokens=300,
            messages=[{"role": "user", "content": prompt}],
        )
        text = "".join(block.text for block in response.content if block.type == "text").strip()
        if not text:
            raise ValueError("Anthropic returned an empty briefing")
        return text

    @staticmethod
    def _deterministic_summary(
        extracted: ExtractedInvoiceData, risk: RiskAssessment, outcome: str, approval_result: str
    ) -> str:
        vendor = extracted.vendor or "an unidentified vendor"
        amount = f"${extracted.amount:,.2f}" if extracted.amount is not None else "an unknown amount"
        po = f"PO {extracted.po_number}" if extracted.po_number else "no PO number on file"
        anomaly_count = len(risk.anomalies)
        anomaly_clause = (
            f"{anomaly_count} anomal{'y' if anomaly_count == 1 else 'ies'} were flagged"
            if anomaly_count
            else "no anomalies were flagged"
        )
        return (
            f"Invoice from {vendor} for {amount} ({po}) was processed with a risk score of "
            f"{risk.risk_score}/100; {anomaly_clause}. Approval result: {approval_result}. "
            f"Final workflow status: {outcome}."
        )
