"""users and organization memberships

Phase 2B.2: user identity + the org<->user<->role linkage.

Design note -- refines PHASE2_COMMERCIAL_ARCHITECTURE.md's original
illustrative `users` DDL (which put org_id/role directly on users, a
one-org-per-user model). This migration instead makes `users` a global
identity table (one account, one row, email globally unique) and
introduces `organization_memberships` as the join table carrying
org_id + role + per-org status. This supports a real-world case the
original design didn't: one person (e.g. a consultant, or Brain OS
support staff) holding memberships -- possibly with different roles --
in more than one organization. The architecture doc's §2 has been
updated to match this as-built shape; see the note there.

Two independent status concepts, deliberately not conflated:
- users.status: account-level (is this login itself active or disabled)
- organization_memberships.status: per-org relationship state
  (invited / active / disabled for that specific org)
A user's account can be active while a specific membership is disabled
(e.g. removed from one org, account still valid for another), and vice
versa is meaningless to allow, so users.status is checked independently
wherever it matters (a later authentication milestone, not this one).

role uses the full six-value enum already locked in
PHASE2_COMMERCIAL_ARCHITECTURE.md §9.2 (owner/admin/finance/ops_manager/
analyst/viewer) -- "basic role placeholder" in this milestone's scope
means the column exists and is validated, not that the authorization
dependency consuming it (require_role(), §9.3/§14) is implemented yet;
that is a later 2B milestone.

No password/credential column is added here: authentication (how a
user proves they are who they say) is an explicitly separate later
milestone (session/authentication, per the locked architecture) and is
out of scope for a table whose job in this milestone is identity +
membership only.

Written as hand-executed raw SQL (op.execute), not op.create_table()/
SQLAlchemy Column objects and not autogenerated from ORM models, per
the locked Phase 2 architecture decision. Does not touch, reference, or
depend on the existing SQLite schema in app/database/connection.py or
any of the original five MVP tables.

Revision ID: 6d389c38a0c8
Revises: fbc84c7b682e
Create Date: 2026-09-05 17:36:42.460354

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d389c38a0c8"
down_revision: Union[str, Sequence[str], None] = "fbc84c7b682e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE users (
            id TEXT PRIMARY KEY,
            email TEXT NOT NULL UNIQUE,
            display_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'disabled')),
            last_login_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE organization_memberships (
            id TEXT PRIMARY KEY,
            org_id TEXT NOT NULL REFERENCES organizations(id),
            user_id TEXT NOT NULL REFERENCES users(id),
            role TEXT NOT NULL
                CHECK (role IN ('owner', 'admin', 'finance', 'ops_manager', 'analyst', 'viewer')),
            status TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('invited', 'active', 'disabled')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (org_id, user_id)
        )
        """
    )
    op.execute("CREATE INDEX idx_organization_memberships_org ON organization_memberships (org_id)")
    op.execute("CREATE INDEX idx_organization_memberships_user ON organization_memberships (user_id)")


def downgrade() -> None:
    op.execute("DROP TABLE organization_memberships")
    op.execute("DROP TABLE users")
