"""migration foundation bootstrap

Phase 2A.2: proves the Alembic pipeline (config load -> connect via
postgres_dsn -> upgrade -> downgrade) works end-to-end against a real
PostgreSQL database, before any commercial domain schema
(organizations/users/plans/freight entities) is introduced in later
milestones.

Creates and drops a single bootstrap table -- deliberately NOT a domain
table. Written as hand-executed raw SQL (op.execute), not
op.create_table()/SQLAlchemy Column objects and not autogenerated from
ORM models, per the locked Phase 2 architecture decision (Alembic for
versioning/rollback only; no ORM adoption in the application).

Does not touch, reference, or depend on the existing SQLite schema in
app/database/connection.py in any way -- that schema lives in a
different database engine entirely and is never migrated by Alembic.

Revision ID: b95ff6be48e7
Revises:
Create Date: 2026-09-05 13:39:30.037614

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b95ff6be48e7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE _migration_foundation_check (
            id SERIAL PRIMARY KEY,
            checked_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE _migration_foundation_check")
