"""organizations table

Phase 2B.1: the first commercial-domain table -- the tenant/client
record every later Phase 2B/2C/2D table hangs off of via org_id. See
PHASE2_COMMERCIAL_ARCHITECTURE.md §1.1 ("Client" and "Organization" are
the same entity) and §2 for the locked DDL this migration implements.

Written as hand-executed raw SQL (op.execute), not op.create_table()/
SQLAlchemy Column objects and not autogenerated from ORM models, per the
locked Phase 2 architecture decision (Alembic for versioning/rollback
only; no ORM adoption in the application).

Two deliberate type refinements vs. the illustrative SQLite-flavored DDL
in the architecture doc, since this migration targets real PostgreSQL:
- financial_visibility_restricted is BOOLEAN (Postgres has a native
  boolean type; the doc's INTEGER was a SQLite illustration).
- created_at is TIMESTAMPTZ DEFAULT now() (Postgres has a native
  timestamp type; the doc's TEXT was a SQLite illustration).
Both are additive precision, not a semantic change -- the same three
facts (id, whether financial visibility is restricted, when the row was
created) are represented, just with the correct native Postgres types.

CHECK constraints on industry_type and status enforce the same closed
value sets the Pydantic schemas in app/models/tenancy_schemas.py
validate at the application layer -- defense in depth, not a
replacement for application validation.

Does not touch, reference, or depend on the existing SQLite schema in
app/database/connection.py or any of the original five MVP tables.

Revision ID: fbc84c7b682e
Revises: b95ff6be48e7
Create Date: 2026-09-05 17:10:22.287742

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fbc84c7b682e"
down_revision: Union[str, Sequence[str], None] = "b95ff6be48e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE organizations (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            industry_type TEXT NOT NULL
                CHECK (industry_type IN ('ecommerce', 'manufacturing', 'retail_distribution')),
            status TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('trial', 'active', 'suspended', 'cancelled')),
            financial_visibility_restricted BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE organizations")
