"use client";

import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { WorkflowStatusBadge, SeverityBadge } from "@/components/dashboard/status-badge";
import { formatCurrency, formatDateTime, formatRelativeTime } from "@/lib/format";
import type { AuditEvent, WorkflowRecord } from "@/lib/types";

const ACTION_LABELS: Record<string, string> = {
  "workflow.start": "Workflow started",
  "document_intelligence.extract": "Fields extracted",
  "risk_engine.assess": "Risk assessed",
  "risk_engine.auto_approve": "Auto-approved",
  "notification.slack": "Slack notified",
  "human_in_loop.decision": "Human decision",
  "executive_briefing.generate": "Briefing generated",
};

interface EvidenceDialogProps {
  workflow: WorkflowRecord | null;
  events: AuditEvent[];
  anchor: Date;
  onOpenChange: (open: boolean) => void;
}

export function EvidenceDialog({ workflow, events, anchor, onOpenChange }: EvidenceDialogProps) {
  return (
    <Dialog open={workflow !== null} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg sm:max-w-xl">
        {workflow && (
          <>
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2 font-mono text-sm font-medium">
                {workflow.workflowId}
              </DialogTitle>
              <DialogDescription>
                Evidence trail for the invoice submitted by {workflow.vendor} ({workflow.poNumber}).
              </DialogDescription>
            </DialogHeader>

            <div className="grid grid-cols-2 gap-3 rounded-lg bg-muted/50 p-3.5 sm:grid-cols-4">
              <Field label="Vendor" value={workflow.vendor} />
              <Field label="Amount" value={formatCurrency(workflow.amount)} />
              <Field label="Risk score" value={`${workflow.riskScore}/100`} />
              <Field label="Status" value={<WorkflowStatusBadge status={workflow.status} />} />
            </div>

            {workflow.anomalies.length > 0 && (
              <div>
                <p className="mb-2 text-xs font-medium uppercase tracking-wide text-muted-foreground">
                  Anomalies detected
                </p>
                <div className="flex flex-col gap-2">
                  {workflow.anomalies.map((a) => (
                    <div key={a.code} className="flex items-start justify-between gap-3 rounded-md border border-border px-3 py-2 text-xs">
                      <span className="text-muted-foreground">{a.detail}</span>
                      <SeverityBadge severity={a.severity} />
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div>
              <p className="mb-2 text-xs font-medium uppercase tracking-wide text-muted-foreground">Audit trail</p>
              <ScrollArea className="h-64 rounded-md border border-border">
                <div className="flex flex-col p-3.5">
                  {events.map((event, i) => (
                    <div key={event.id} className="relative flex gap-3 pb-4 last:pb-0">
                      {i < events.length - 1 && (
                        <span className="absolute left-[5px] top-3 h-full w-px bg-border" />
                      )}
                      <span className="relative mt-1.5 size-2.5 shrink-0 rounded-full bg-primary ring-4 ring-card" />
                      <div className="flex-1">
                        <div className="flex items-center justify-between gap-2">
                          <p className="text-sm font-medium text-foreground">{ACTION_LABELS[event.action] ?? event.action}</p>
                          <span className="whitespace-nowrap text-[11px] text-muted-foreground" title={formatDateTime(event.timestamp)}>
                            {formatRelativeTime(event.timestamp, anchor)}
                          </span>
                        </div>
                        <p className="text-xs capitalize text-muted-foreground">{event.status.replaceAll("_", " ")}</p>
                        {event.detail && <p className="mt-1 text-xs text-muted-foreground">{event.detail}</p>}
                      </div>
                    </div>
                  ))}
                </div>
              </ScrollArea>
            </div>

            <Separator />
            <p className="text-[11px] text-muted-foreground">
              {workflow.briefingGeneratedBy === null ? (
                "Executive briefing not yet generated -- pending human approval."
              ) : (
                <>
                  Generated by{" "}
                  {workflow.briefingGeneratedBy === "anthropic" ? "Anthropic executive briefing" : "deterministic fallback template"}
                </>
              )}
              {workflow.approvedBy && <> · Decision recorded by {workflow.approvedBy}</>}
            </p>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}

function Field({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-[11px] text-muted-foreground">{label}</span>
      <span className="text-sm font-medium text-foreground">{value}</span>
    </div>
  );
}
